version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: stasis-backend
    ports:
      - "8080:8080"
    environment:
      # Add any backend environment variables here
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stasis-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
