services:
  # Spring Boot Backend (using Supabase database)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stasis-backend
    environment:
      SPRING_PROFILES_ACTIVE: supabase
      # JVM settings for better container performance
      JAVA_OPTS: "-Xmx512m -Xms256m -XX:+UseContainerSupport"
    ports:
      - "8080:8080"
    networks:
      - stasis-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s

  # React Frontend with Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stasis-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - stasis-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  stasis-network:
    driver: bridge
